### ISSUE TITLE
Electron app won't connect to WeeChat instance on LAN / JavaScript error

### ISSUE THREAD

**Issue by hrvstr** [glowing-bear/glowing-bear#1106]
So I just build the electron app for mac OS with this terminal output:

```
npm install; npm install electron-packager; npm run build-electron-darwin
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> phantomjs-prebuilt@2.1.16 install /Users/HRVSTR/Downloads/glowing-bear/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
Writing location.js file
PhantomJS is already installed on PATH at /usr/local/bin/phantomjs

> core-js@3.6.4 postinstall /Users/HRVSTR/Downloads/glowing-bear/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> glowing-bear@0.8.0 postinstall /Users/HRVSTR/Downloads/glowing-bear
> bower install -p

bower angular-sanitize#1.7.x       not-cached https://github.com/angular/bower-angular-sanitize.git#1.7.x
bower angular-sanitize#1.7.x          resolve https://github.com/angular/bower-angular-sanitize.git#1.7.x
bower angular#1.7.x                not-cached https://github.com/angular/bower-angular.git#1.7.x
bower angular#1.7.x                   resolve https://github.com/angular/bower-angular.git#1.7.x
bower angular-route#1.7.x          not-cached https://github.com/angular/bower-angular-route.git#1.7.x
bower angular-route#1.7.x             resolve https://github.com/angular/bower-angular-route.git#1.7.x
bower angular-loader#1.7.x         not-cached https://github.com/angular/bower-angular-loader.git#1.7.x
bower angular-loader#1.7.x            resolve https://github.com/angular/bower-angular-loader.git#1.7.x
bower underscore#~1.9              not-cached https://github.com/jashkenas/underscore.git#~1.9
bower underscore#~1.9                 resolve https://github.com/jashkenas/underscore.git#~1.9
bower angular-mocks#1.7.x          not-cached https://github.com/angular/bower-angular-mocks.git#1.7.x
bower angular-mocks#1.7.x             resolve https://github.com/angular/bower-angular-mocks.git#1.7.x
bower angular-touch#1.7.x          not-cached https://github.com/angular/bower-angular-touch.git#1.7.x
bower angular-touch#1.7.x             resolve https://github.com/angular/bower-angular-touch.git#1.7.x
bower underscore#~1.9                download https://github.com/jashkenas/underscore/archive/1.9.2.tar.gz
bower angular-loader#1.7.x           download https://github.com/angular/bower-angular-loader/archive/v1.7.9.tar.gz
bower angular-sanitize#1.7.x         download https://github.com/angular/bower-angular-sanitize/archive/v1.7.9.tar.gz
bower angular#1.7.x                  download https://github.com/angular/bower-angular/archive/v1.7.9.tar.gz
bower angular-route#1.7.x            download https://github.com/angular/bower-angular-route/archive/v1.7.9.tar.gz
bower angular-touch#1.7.x            download https://github.com/angular/bower-angular-touch/archive/v1.7.9.tar.gz
bower angular-mocks#1.7.x            download https://github.com/angular/bower-angular-mocks/archive/v1.7.9.tar.gz
bower angular-route#1.7.x             extract archive.tar.gz
bower angular-route#1.7.x            resolved https://github.com/angular/bower-angular-route.git#1.7.9
bower angular-loader#1.7.x            extract archive.tar.gz
bower angular-loader#1.7.x           resolved https://github.com/angular/bower-angular-loader.git#1.7.9
bower angular-sanitize#1.7.x          extract archive.tar.gz
bower angular-sanitize#1.7.x         resolved https://github.com/angular/bower-angular-sanitize.git#1.7.9
bower underscore#~1.9                 extract archive.tar.gz
bower angular#1.7.x                   extract archive.tar.gz
bower angular-touch#1.7.x             extract archive.tar.gz
bower angular-touch#1.7.x            resolved https://github.com/angular/bower-angular-touch.git#1.7.9
bower angular-mocks#1.7.x             extract archive.tar.gz
bower angular-mocks#1.7.x            resolved https://github.com/angular/bower-angular-mocks.git#1.7.9
bower angular#1.7.x                  resolved https://github.com/angular/bower-angular.git#1.7.9
bower underscore#~1.9                resolved https://github.com/jashkenas/underscore.git#1.9.2
bower angular-route#1.7.x             install angular-route#1.7.9
bower angular-loader#1.7.x            install angular-loader#1.7.9
bower angular-sanitize#1.7.x          install angular-sanitize#1.7.9
bower angular-touch#1.7.x             install angular-touch#1.7.9
bower angular-mocks#1.7.x             install angular-mocks#1.7.9
bower angular#1.7.9                   install angular#1.7.9
bower underscore#~1.9                 install underscore#1.9.2

angular-route#1.7.9 bower_components/angular-route
└── angular#1.7.9

angular-loader#1.7.9 bower_components/angular-loader
└── angular#1.7.9

angular-sanitize#1.7.9 bower_components/angular-sanitize
└── angular#1.7.9

angular-touch#1.7.9 bower_components/angular-touch
└── angular#1.7.9

angular-mocks#1.7.9 bower_components/angular-mocks
└── angular#1.7.9

angular#1.7.9 bower_components/angular

underscore#1.9.2 bower_components/underscore
npm notice created a lockfile as package-lock.json. You should commit this file.
added 442 packages from 841 contributors and audited 976 packages in 13.516s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

+ electron-packager@14.2.1
updated 1 package and audited 976 packages in 3.975s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> glowing-bear@0.8.0 build-electron-darwin /Users/HRVSTR/Downloads/glowing-bear
> make -f electron.makefile bower build-electron-darwin

bower install
bower bootstrap#~3.3        not-cached https://github.com/twbs/bootstrap.git#~3.3
bower bootstrap#~3.3           resolve https://github.com/twbs/bootstrap.git#~3.3
bower html5-boilerplate#~4.3.0       not-cached https://github.com/h5bp/html5-boilerplate.git#~4.3.0
bower html5-boilerplate#~4.3.0          resolve https://github.com/h5bp/html5-boilerplate.git#~4.3.0
bower emojione#~2.2                  not-cached https://github.com/Ranks/emojione.git#~2.2
bower emojione#~2.2                     resolve https://github.com/Ranks/emojione.git#~2.2
bower html5-boilerplate#~4.3.0         download https://github.com/h5bp/html5-boilerplate/archive/v4.3.0.tar.gz
bower bootstrap#~3.3                   download https://github.com/twbs/bootstrap/archive/v3.3.7.tar.gz
bower emojione#~2.2                    download https://github.com/Ranks/emojione/archive/v2.2.7.tar.gz
bower html5-boilerplate#~4.3.0          extract archive.tar.gz
bower html5-boilerplate#~4.3.0         resolved https://github.com/h5bp/html5-boilerplate.git#4.3.0
bower bootstrap#~3.3                    extract archive.tar.gz
bower bootstrap#~3.3                   resolved https://github.com/twbs/bootstrap.git#3.3.7
bower jquery#1.9.1 - 3               not-cached https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower jquery#1.9.1 - 3                  resolve https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower jquery#1.9.1 - 3                 download https://github.com/jquery/jquery-dist/archive/3.4.1.tar.gz
bower jquery#1.9.1 - 3                  extract archive.tar.gz
bower jquery#1.9.1 - 3                 resolved https://github.com/jquery/jquery-dist.git#3.4.1
bower emojione#~2.2                    progress received 26.3MB
bower emojione#~2.2                    progress received 30.4MB
bower emojione#~2.2                    progress received 37.1MB
bower emojione#~2.2                    progress received 42.9MB
bower emojione#~2.2                    progress received 48.7MB
bower emojione#~2.2                    progress received 54.5MB
bower emojione#~2.2                    progress received 60.3MB
bower emojione#~2.2                    progress received 66.1MB
bower emojione#~2.2                    progress received 71.9MB
bower emojione#~2.2                    progress received 77.7MB
bower emojione#~2.2                    progress received 83.5MB
bower emojione#~2.2                    progress received 89.3MB
bower emojione#~2.2                     extract archive.tar.gz
bower emojione#~2.2                    resolved https://github.com/Ranks/emojione.git#2.2.7
bower html5-boilerplate#~4.3.0          install html5-boilerplate#4.3.0
bower bootstrap#~3.3                    install bootstrap#3.3.7
bower jquery#1.9.1 - 3                  install jquery#3.4.1
bower emojione#~2.2                     install emojione#2.2.7

html5-boilerplate#4.3.0 bower_components/html5-boilerplate

bootstrap#3.3.7 bower_components/bootstrap
└── jquery#3.4.1

jquery#3.4.1 bower_components/jquery

emojione#2.2.7 bower_components/emojione
find bower_components \( -name "*min.js" -o -name "*min.css" \) -exec cp {} 3rdparty \;
cp -r bower_components/bootstrap/fonts .
cp bower_components/emojione/assets/sprites/emojione.sprites.svg 3rdparty
sed -i.bak 's,https://cdnjs.cloudflare.com/ajax/libs/[^\"]*/,3rdparty/,g' index.html
sed -i.bak 's, integrity=\".*\" crossorigin=\"anonymous\",,' index.html
electron-packager . "Glowing Bear" --overwrite --version-string.FileDescription="Glowing Bear" --ignore=node_modules --ignore=test --ignore=bower_components --platform=darwin --arch=x64 --electron-version=8.0.1 --icon=assets/img/glowing-bear.icns
Packaging app for platform darwin x64 using electron v8.0.1
Wrote new app to /Users/HRVSTR/Downloads/glowing-bear/Glowing Bear-darwin-x64
```

The app launches fine but it won't connect to my WeChat instance on another host on the LAN. Using the browser version from http://latest.glowing-bear.org works.

When I quit the app I get this error message:

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: EACCES: permission denied, open 'init.json'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at BrowserWindow.<anonymous> (/Users/HRVSTR/Downloads/glowing-bear/Glowing Bear-darwin-x64/Glowing Bear.app/Contents/Resources/app/electron-main.js:64:8)
    at BrowserWindow.emit (events.js:210:5)
```

![Bildschirmfoto 2020-02-25 um 11 30 22](https://user-images.githubusercontent.com/4610008/75239599-4240be80-57c3-11ea-983d-ac189104d1d9.png)

**Comment by lorenzhs** [comment]
@torhve looks like it's caused by our choice of preference file, https://github.com/glowing-bear/glowing-bear/blob/5bdfa455d8551a879a6f422e2201bdcf3e18340a/electron-main.js#L12. Any ideas?

**Comment by lorenzhs** [comment]
@hrvstr what's the status on this?

**Comment by hrvstr** [comment]
I tried commenting out said line and re-build the app but the error message still appears. More importantly I still can't connect via the app or a self hosted instance (running via python SimpleHTTPServer). Even when it is running on the same box.

The console shows the following log:
```
DevTools failed to parse SourceMap: file:///Users/HRVSTR/Development/glowing-bear/Glowing%20Bear-darwin-x64/Glowing%20Bear.app/Contents/Resources/app/3rdparty/angular.min.js.map
DevTools failed to parse SourceMap: file:///Users/HRVSTR/Development/glowing-bear/Glowing%20Bear-darwin-x64/Glowing%20Bear.app/Contents/Resources/app/3rdparty/angular-route.min.js.map
DevTools failed to parse SourceMap: file:///Users/HRVSTR/Development/glowing-bear/Glowing%20Bear-darwin-x64/Glowing%20Bear.app/Contents/Resources/app/3rdparty/angular-sanitize.min.js.map
DevTools failed to parse SourceMap: file:///Users/HRVSTR/Development/glowing-bear/Glowing%20Bear-darwin-x64/Glowing%20Bear.app/Contents/Resources/app/3rdparty/angular-touch.min.js.map
DevTools failed to parse SourceMap: file:///Users/HRVSTR/Development/glowing-bear/Glowing%20Bear-darwin-x64/Glowing%20Bear.app/Contents/Resources/app/3rdparty/bootstrap.min.css.map
angular.min.js:127 Notification permission status:  granted
websockets.js:121 WebSocket connection to 'ws://dietpi:9001/weechat' failed: Error during WebSocket handshake: Unexpected response code: 403
connect @ websockets.js:121
connect @ connection.js:306
$scope.connect @ glowingbear.js:732
fn @ VM93:4
e @ angular.min.js:198
$eval @ angular.min.js:154
$apply @ angular.min.js:154
(anonymous) @ angular.min.js:198
sg @ angular.min.js:40
d @ angular.min.js:40
angular.min.js:127 Relay error Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
(anonymous) @ angular.min.js:127
onerror @ connection.js:288
error (async)
connect @ websockets.js:124
connect @ connection.js:306
$scope.connect @ glowingbear.js:732
fn @ VM93:4
e @ angular.min.js:198
$eval @ angular.min.js:154
$apply @ angular.min.js:154
(anonymous) @ angular.min.js:198
sg @ angular.min.js:40
d @ angular.min.js:40
angular.min.js:127 Disconnected from relay

```

**Comment by lorenzhs** [comment]
> websockets.js:121 WebSocket connection to 'ws://dietpi:9001/weechat' failed: Error during WebSocket handshake: Unexpected response code: 403

seems like there's a problem with your setup if you're getting a 403 error code ("forbidden"), can you try `http://dietpi:9001/weechat` in your browser and see if you get an error (bad) or an endlessly loading blank page (good)?

**Comment by lorenzhs** [comment]
Oh, does electron maybe forbid insecure websockets now? That would explain things. @torhve do you know something about that?

**Comment by hrvstr** [comment]
> > websockets.js:121 WebSocket connection to 'ws://dietpi:9001/weechat' failed: Error during WebSocket handshake: Unexpected response code: 403
> 
> seems like there's a problem with your setup if you're getting a 403 error code ("forbidden"), can you try `http://dietpi:9001/weechat` in your browser and see if you get an error (bad) or an endlessly loading blank page (good)?

- Chrome gives a `HTTP ERROR 400`
- Firefox and Safari load a blank page (no errors in console)
- Page load is fast

**Comment by AStove** [comment]
You haven't set `relay.network.websocket_allowed_origins` in weechat, have you?

**Comment by hrvstr** [comment]
Damn... of course I had it set to "http://latest.glowing-bear.org". After unsetting the value I am able to connect.
