### ISSUE TITLE
Electron build fails on mac OS (No rule to make target `bower')

### ISSUE THREAD

**Issue by hrvstr** [glowing-bear/glowing-bear#1177]
I just tried to build the Electron app for mac OS but failed because of this error: `No rule to make target 'bower'` There were also some missing dependencies that I tried to install manually. Sorry for the wall of text but I thought it might be useful for debugging.

## Setup
- mac OS Mojave 10.14.6 (18G6042)
- node v15.5.0
- npm 6.14.11

### Clone the repo
```
git clone https://github.com/glowing-bear/glowing-bear.git
cd glowing-bear/
```

### Install modules
```
npm install

> fsevents@1.2.13 install /Users/HRVSTR/Downloads/glowing-bear/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/HRVSTR/Downloads/glowing-bear/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:133:18)
    at Object.runInThisContext (node:vm:310:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/HRVSTR/Downloads/glowing-bear/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/15.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/HRVSTR/Downloads/glowing-bear/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v15.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> core-js@3.8.0 postinstall /Users/HRVSTR/Downloads/glowing-bear/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 1083 packages from 1150 contributors and audited 1083 packages in 10.013s

found 0 vulnerabilities
```

### Install `nan`
```
npm install nan
npm WARN karma-webpack@5.0.0-alpha.3.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of jquery@>= 1.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

+ nan@2.14.2
added 3 packages from 8 contributors and audited 1086 packages in 4.358s

found 0 vulnerabilities
```

#### webpack
```
npm install webpack@^4.0.0 --save
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.2.13 install /Users/HRVSTR/Downloads/glowing-bear/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm WARN linkifyjs@2.1.9 requires a peer of jquery@>= 1.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.

+ webpack@4.46.0
added 170 packages from 98 contributors, removed 15 packages, updated 9 packages and audited 1241 packages in 12.075s

found 0 vulnerabilities
```

#### jquery
```
npm install jquery --save
npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.

+ jquery@3.5.1
added 1 package from 1 contributor and audited 1242 packages in 4.734s

found 0 vulnerabilities
```

#### react
```
npm install react --save
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.

+ react@17.0.1
added 2 packages from 1 contributor and audited 1244 packages in 4.451s

found 0 vulnerabilities
```

#### react-dom
```
npm install react-dom --save
+ react-dom@17.0.1
added 2 packages and audited 1246 packages in 4.812s

found 0 vulnerabilities
```

### Install `electron-packager`
```
npm install electron-packager

> core-js@3.8.3 postinstall /Users/HRVSTR/Downloads/glowing-bear/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

+ electron-packager@15.2.0
added 1 package, removed 4 packages, updated 11 packages and audited 1243 packages in 9.021s

found 0 vulnerabilities
```

## Build for mac OS
```
npm run build-electron-darwin

> glowing-bear@0.10.0 build-electron-darwin /Users/HRVSTR/Downloads/glowing-bear
> make -f electron.makefile bower build-electron-darwin

make: *** No rule to make target `bower'.  Stop.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! glowing-bear@0.10.0 build-electron-darwin: `make -f electron.makefile bower build-electron-darwin`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the glowing-bear@0.10.0 build-electron-darwin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/HRVSTR/.npm/_logs/2021-01-21T10_35_45_701Z-debug.log
```

### Complete log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/15.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-electron-darwin'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v15.5.0
4 verbose run-script [
4 verbose run-script   'prebuild-electron-darwin',
4 verbose run-script   'build-electron-darwin',
4 verbose run-script   'postbuild-electron-darwin'
4 verbose run-script ]
5 info lifecycle glowing-bear@0.10.0~prebuild-electron-darwin: glowing-bear@0.10.0
6 info lifecycle glowing-bear@0.10.0~build-electron-darwin: glowing-bear@0.10.0
7 verbose lifecycle glowing-bear@0.10.0~build-electron-darwin: unsafe-perm in lifecycle true
8 verbose lifecycle glowing-bear@0.10.0~build-electron-darwin: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/HRVSTR/Downloads/glowing-bear/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle glowing-bear@0.10.0~build-electron-darwin: CWD: /Users/HRVSTR/Downloads/glowing-bear
10 silly lifecycle glowing-bear@0.10.0~build-electron-darwin: Args: [ '-c', 'make -f electron.makefile bower build-electron-darwin' ]
11 silly lifecycle glowing-bear@0.10.0~build-electron-darwin: Returned: code: 2  signal: null
12 info lifecycle glowing-bear@0.10.0~build-electron-darwin: Failed to exec build-electron-darwin script
13 verbose stack Error: glowing-bear@0.10.0 build-electron-darwin: `make -f electron.makefile bower build-electron-darwin`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:376:20)
13 verbose stack     at maybeClose (node:internal/child_process:1063:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
14 verbose pkgid glowing-bear@0.10.0
15 verbose cwd /Users/HRVSTR/Downloads/glowing-bear
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/15.5.0/bin/node" "/usr/local/bin/npm" "run" "build-electron-darwin"
18 verbose node v15.5.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 2
22 error glowing-bear@0.10.0 build-electron-darwin: `make -f electron.makefile bower build-electron-darwin`
22 error Exit status 2
23 error Failed at the glowing-bear@0.10.0 build-electron-darwin script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by lorenzhs** [comment]
Looks like 823a327881e743bc3d2ab01fbca232ecdea8d509 didn't remove the `bower` dependency from the build script, should be fixed now. Can you try again?

You shouldn't have to manually install any dependencies, though. I just did a fresh clone and `npm install` followed by `npm run-script build-electron-linux` worked fine.

**Comment by hrvstr** [comment]
> I just did a fresh clone and `npm install` followed by `npm run-script build-electron-linux` worked fine.

Thanks, working fine here as well!
