### ISSUE TITLE
build-electron-linux fails with `UnhandledPromiseRejectionWarning: Unhandled promise rejection.`

### ISSUE THREAD

**Issue by saywebsolutions** [glowing-bear/glowing-bear#1182]
```
$ npm run build-electron-linux

> glowing-bear@0.10.0 build-electron-linux /home/user/repos/glowing-bear
> make -f electron.makefile build-electron-linux

npm run build

> glowing-bear@0.10.0 build /home/user/repos/glowing-bear
> webpack

(node:2436494) UnhandledPromiseRejectionWarning: Error: No valid exports main found for '/home/user/repos/glowing-bear/node_modules/colorette'
at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
at applyExports (internal/modules/cjs/loader.js:499:14)
at resolveExports (internal/modules/cjs/loader.js:548:12)
at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
at Function.Module._load (internal/modules/cjs/loader.js:854:27)
at Module.require (internal/modules/cjs/loader.js:1023:19)
at require (/home/user/repos/glowing-bear/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
at Object.get colors [as colors] (/home/user/repos/glowing-bear/node_modules/webpack-cli/lib/utils/index.js:3:16)
at Object.error (/home/user/repos/glowing-bear/node_modules/webpack-cli/lib/utils/logger.js:5:58)
at runCLI (/home/user/repos/glowing-bear/node_modules/webpack-cli/lib/bootstrap.js:13:22)
(node:2436494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2436494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
electron-packager ./build "Glowing Bear" --overwrite --version-string.FileDescription="Glowing Bear" --ignore=node_modules --ignore=test --ignore=bower_components --platform=linux --arch=x64 --electron-version=9.0.5 --icon=assets/img/favicon.ico
Packaging app for platform linux x64 using electron v9.0.5
ENOENT: no such file or directory, stat './build'
make: *** [electron.makefile:25: build-electron-linux] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! glowing-bear@0.10.0 build-electron-linux: `make -f electron.makefile build-electron-linux`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the glowing-bear@0.10.0 build-electron-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-03-17T19_30_27_155Z-debug.log
```

**Comment by lorenzhs** [comment]
I can't reproduce this. What version of nodejs are you using? Fwiw, I'm on v14.15.4.

**Comment by saywebsolutions** [comment]
my apologies, i was on a previous LTS of node. works fine after updating, thank you
