### ISSUE TITLE
Failing to build Linux app on Ubuntu 22.04.2 LTS and Node.js v18.17.0

### ISSUE THREAD

**Issue by TehPeGaSuS** [glowing-bear/glowing-bear#1267]
**Node version:**
```
vitor@EliteDesk:~/GitHub$ node -v
v18.17.0
```
**Repo cloning:**
```
vitor@EliteDesk:~/GitHub$ git clone --recurse-submodules https://github.com/glowing-bear/glowing-bear.git
Cloning into 'glowing-bear'...
remote: Enumerating objects: 9344, done.
remote: Counting objects: 100% (547/547), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 9344 (delta 333), reused 422 (delta 253), pack-reused 8797
Receiving objects: 100% (9344/9344), 6.40 MiB | 17.91 MiB/s, done.
Resolving deltas: 100% (5866/5866), done.
```
### After entering `glowing-bear` folder
**Install dependencies:**
```
vitor@EliteDesk:~/GitHub/glowing-bear$ npm install
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated angular-touch@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular-sanitize@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular-route@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated protractor@7.0.0: We have news to share - Protractor is deprecated and will reach end-of-life by Summer 2023. To learn more and find out about other options please refer to this post on the Angular blog. Thank you for using and contributing to Protractor. https://goo.gle/state-of-e2e-in-angular

added 743 packages, and audited 744 packages in 17s

70 packages are looking for funding
  run `npm fund` for details

9 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 9.6.7 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice
```
**Install electron-packager:**
```
$ npm install electron-packager

added 129 packages, and audited 873 packages in 12s

91 packages are looking for funding
  run `npm fund` for details

9 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
**Run electron builder**
```
$ npm run build-electron-linux
npm ERR! Missing script: "build-electron-linux"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/vitor/.npm/_logs/2023-08-03T12_06_57_856Z-debug-0.log
```
### Debug log
```
vitor@EliteDesk:~/GitHub/glowing-bear$ cat /home/vitor/.npm/_logs/2023-08-03T12_06_57_856Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/vitor/GitHub/glowing-bear/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/vitor/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 11ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm run build-electron-linux
21 verbose argv "run" "build-electron-linux"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:/home/vitor/.npm/_logs/2023-08-03T12_06_57_856Z-
26 verbose logfile /home/vitor/.npm/_logs/2023-08-03T12_06_57_856Z-debug-0.log
27 timing npm:load:logFile Completed in 12ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 33ms
31 silly logfile done cleaning log files
32 timing command:run Completed in 34ms
33 verbose stack Error: Missing script: "build-electron-linux"
33 verbose stack
33 verbose stack To see a list of scripts, run:
33 verbose stack   npm run
33 verbose stack     at RunScript.run (/usr/lib/node_modules/npm/lib/commands/run-script.js:93:13)
33 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:89:5)
34 verbose cwd /home/vitor/GitHub/glowing-bear
35 verbose Linux 5.19.0-50-generic
36 verbose node v18.17.0
37 verbose npm  v9.6.7
38 error Missing script: "build-electron-linux"
38 error
38 error To see a list of scripts, run:
38 error   npm run
39 verbose exit 1
40 timing npm Completed in 129ms
41 verbose code 1
```

**Comment by txdv** [comment]
```
33 verbose stack Error: Missing script: "build-electron-linux"
```

There is no such step as build-electron-linux

**Comment by TehPeGaSuS** [comment]
Then the `Install app` bit on [https://glowing-bear.org/index.html](https://glowing-bear.org/index.html) should be updated to reflect that, since I was using that guide.

Cheers

**Comment by txdv** [comment]
It is now this:
```bash
npm run tauri
```

although it failed for me straight away and because it lacked librsvg2-dev, so on my system it was
```bash
sudo apt-get install librsvg2-dev
npm run tauri --verbose
```

It has been actually removed https://github.com/glowing-bear/glowing-bear/commit/3d3377b6865495397f08eb5adda38df8e7bc36a0 its just in the development branch and not yet released

**Comment by TehPeGaSuS** [comment]
Fair enough!

Closing as `Completed`.
