### ISSUE TITLE
Fix issue where many connections are opened

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#741]
@weechatter had a mysterious issue where Glowing Bear would rack up loads of connections in a loop. From his logs (Android app at https://github.com/glowing-bear/glowing-bear/tree/df23985cdacd3c2ba748410ff2c526f26a1b6c2d)

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
angular.min.js:102 Service Worker is supported
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Service Worker err: DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.
angular.min.js:102 Connected to relay
2angular.min.js:102 Fetching  42  lines
http://fooo.bar/baz.png Failed to load resource: the server responded with a status of 404 (Not Found)
2http://pbs.twimg.com/media/foobar.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:102 Disconnecting from relay
angular.min.js:102 Disconnected from relay
angular.min.js:102 Service Worker is supported
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Service Worker err: DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.
angular.min.js:102 Connected to relay
angular.min.js:102 Fetching  42  lines
2angular.min.js:102 Fetching  Infinity  lines
angular.min.js:102 Fetching  35  lines
angular.min.js:102 Unhandled event received: _buffer_cleared
4angular.min.js:102 Fetching  35  lines
angular.min.js:102 Fetching  61  lines
angular.min.js:102 Fetching  51  lines
angular.min.js:102 Fetching  32  lines
8angular.min.js:102 Unhandled event received: _buffer_cleared
4angular.min.js:102 ReferenceError: emojione is not defined
    at m.$scope.inputChanged (inputbar.js:29)
    at angular.min.js:200
    at m.$eval (angular.min.js:126)
    at angular.min.js:216
    at angular.min.js:228
    at q (angular.min.js:7)
    at $$writeModelToScope (angular.min.js:228)
    at angular.min.js:227
    at h (angular.min.js:226)
    at f (angular.min.js:226)(anonymous function) @ angular.min.js:102(anonymous function) @ angular.min.js:76(anonymous function) @ angular.min.js:228q @ angular.min.js:7$$writeModelToScope @ angular.min.js:228(anonymous function) @ angular.min.js:227h @ angular.min.js:226f @ angular.min.js:226$$runValidators @ angular.min.js:226$$parseAndValidate @ angular.min.js:227$commitViewValue @ angular.min.js:226(anonymous function) @ angular.min.js:228m.$eval @ angular.min.js:126m.$apply @ angular.min.js:127$$debounceViewValueCommit @ angular.min.js:228$setViewValue @ angular.min.js:228l @ angular.min.js:155c @ angular.min.js:32
angular.min.js:102 Unhandled event received: _buffer_cleared
angular.min.js:102 Disconnecting from relay
angular.min.js:102 Disconnected from relay
angular.min.js:102 Service Worker is supported
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Service Worker err: DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.
websockets.js:121 WebSocket connection to 'ws://foo.bar:1234/weechat' failed: Connection closed before receiving a handshake response
angular.min.js:102 Relay error Event {isTrusted: true}(anonymous function) @ angular.min.js:102onerror @ connection.js:156
angular.min.js:102 Disconnected from relay
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
websockets.js:121 WebSocket connection to 'ws://foo.bar:1234/weechat' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
angular.min.js:102 Relay error Event {isTrusted: true}(anonymous function) @ angular.min.js:102onerror @ connection.js:156
angular.min.js:102 Disconnected from relay
angular.min.js:102 Attempting to reconnect...
```

the last bits of the above is repeated many times in slight variations. Sometimes, it's even more obvious:

```
angular.min.js:102 Disconnected from relay
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
angular.min.js:102 Attempting to reconnect...
angular.min.js:102 Connecting to URL:  ws://foo.bar:1234/weechat
websockets.js:121 WebSocket connection to 'ws://foo.bar:1234/weechat' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
angular.min.js:102 Relay error Event {isTrusted: true}(anonymous function) @ angular.min.js:102onerror @ connection.js:156
```

At the end is this portion, which might also be of interest:

```
angular.min.js:102 Fetching  33  lines
angular.min.js:102 Fetching  33  lines
angular.min.js:102 Sucessfully reconnected to relay
angular.min.js:102 Connected to relay
angular.min.js:102 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.19/ngRepeat/dupes?p0=part%20in%20activeBuffer().title&p1=string%3Af&p2=f
    at Error (native)
    at file:///android_asset/www/3rdparty/angular.min.js:6:417
    at file:///android_asset/www/3rdparty/angular.min.js:235:269
    at Object.fn (file:///android_asset/www/3rdparty/angular.min.js:123:151)
    at m.$digest (file:///android_asset/www/3rdparty/angular.min.js:124:232)
    at m.$apply (file:///android_asset/www/3rdparty/angular.min.js:127:148)
    at onmessage (file:///android_asset/www/js/websockets.js:113:20)
    at WebSocket.ws.onmessage (file:///android_asset/www/js/websockets.js:130:17)(anonymous function) @ angular.min.js:102(anonymous function) @ angular.min.js:76m.$digest @ angular.min.js:124m.$apply @ angular.min.js:127onmessage @ websockets.js:113ws.onmessage @ websockets.js:130
angular.min.js:102 Sucessfully reconnected to relay
```

I anonymized the logs.

There's at least one other bug happening there, too: `2angular.min.js:102 Fetching  Infinity  lines`. I don't know what's causing the bit at the end.

**Comment by lorenzhs** [comment]
Fixing #740 would probably fix this as well

**Comment by lorenzhs** [comment]
Closing since it hasn't happened again since merging #770
