### ISSUE TITLE
ClassNotFoundException when instantiating Cordova receiver

### ISSUE THREAD

**Issue by vt0r** [glowing-bear/glowing-bear#755]
Getting a fatal exception on boot (below) when Android boots and Glowing Bear attempts to start a Cordova receiver (`de.appplant.cordova.plugin.localnotification.Restore`). It appears as if the app is missing Cordova libs for arm64, but I haven't dug much further than the error message itself. I'll update the issue if I can get any additional information.

### Steps to reproduce
1. None. Happens at every boot of the system when Glowing Bear is started.

### Environment
Glowing Bear version: latest Google Play Store version

Android version: 6.0.1

Device: Nexus 6P

### Crash logs
```
03-17 00:57:04.428 E/AndroidRuntime(12278): FATAL EXCEPTION: main
03-17 00:57:04.428 E/AndroidRuntime(12278): Process: com.glowing_bear, PID: 12278
03-17 00:57:04.428 E/AndroidRuntime(12278): java.lang.RuntimeException: Unable to instantiate receiver de.appplant.cordova.plugin.localnotification.Restore: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.localnotification.Restore" on path: DexPathList[[zip file "/data/app/com.glowing_bear-1/base.apk"],nativeLibraryDirectories=[/data/app/com.glowing_bear-1/lib/arm64, /vendor/lib64, /system/lib64]]
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2706)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.os.Looper.loop(Looper.java:148)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.app.ActivityThread.main(ActivityThread.java:5422)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at java.lang.reflect.Method.invoke(Native Method)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-17 00:57:04.428 E/AndroidRuntime(12278): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.localnotification.Restore" on path: DexPathList[[zip file "/data/app/com.glowing_bear-1/base.apk"],nativeLibraryDirectories=[/data/app/com.glowing_bear-1/lib/arm64, /vendor/lib64, /system/lib64]]
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)
03-17 00:57:04.428 E/AndroidRuntime(12278): 	... 8 more
03-17 00:57:04.428 E/AndroidRuntime(12278): 	Suppressed: java.lang.ClassNotFoundException: de.appplant.cordova.plugin.localnotification.Restore
03-17 00:57:04.428 E/AndroidRuntime(12278): 		at java.lang.Class.classForName(Native Method)
03-17 00:57:04.428 E/AndroidRuntime(12278): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-17 00:57:04.428 E/AndroidRuntime(12278): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-17 00:57:04.428 E/AndroidRuntime(12278): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-17 00:57:04.428 E/AndroidRuntime(12278): 		... 10 more
03-17 00:57:04.428 E/AndroidRuntime(12278): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by lorenzhs** [comment]
This issue would have been better suited for https://github.com/glowing-bear/glowing-bear-cordova. It should be fixed in master (commit https://github.com/glowing-bear/glowing-bear-cordova/commit/6ea71c5f5a657ad54dd50660b668f1ff2898a0f3), I thought I'd made a new release but apparently I forgot. Sorry, I'll do it tonight.

**Comment by lorenzhs** [comment]
Moved to https://github.com/glowing-bear/glowing-bear-cordova/issues/10
