### ISSUE TITLE
Exception Cannot read property 'requestedLines' of undefined

### ISSUE THREAD

**Issue by torhve** [glowing-bear/glowing-bear#771]
Saw this error immiediately after connecting, gb reconnected and worked fine after that.

```
Cannot read property 'requestedLines' of undefined  at handleLine (js/handlers.js:142:15)
    at js/handlers.js:228:13
    at Array.forEach (native)
    at Object.handleBufferLineAdded [as _buffer_line_added] (handlers.js:227:36)
```

**Comment by AStove** [comment]
Yes, still exists.
![image](https://user-images.githubusercontent.com/23409814/71329110-02d6c700-2521-11ea-8c65-e3b48c22dcae.png)
